### ISSUE TITLE
Lägga till titlar med information:

### ISSUE THREAD

**Issue by TE4-emanuel-strom** [itggot-TE4/Yabs#135]
- isbn
- title

Använd google isbn api

Use faker api for mocking

# Context
Related to #96

**Comment by itggot-linus-styren** [comment]
Talk to @itggot-TE4/blue-team regarding usage in Library System.

**Comment by itggot-linus-styren** [comment]
Questions to answer:
- Should the API be used from the frontend to display images etc?
- -||- from the backend to store cost/isbn etc?
- Does the architecture need to be changed in anyway to meet customer requirements?
