### ISSUE TITLE
Registrera böcker med unik streckkod för skönlitteratur.

### ISSUE THREAD

**Issue by TE4-emanuel-strom** [itggot-TE4/Yabs#136]
# Description
Staff users should be able to register books with "skönlitteratur"

## DoD
-TBD

## Discuss with PO
- ~~need clerification on issue~~

## Context
Related to #34
~~Possible duplicate of #135~~
Discuss with @itggot-TE4/green-team regarding #161

**Comment by itggot-daniel-berg** [comment]
What needs to be clarified?

**Comment by TE4-emanuel-strom** [comment]
Is "böcker" in this context what we previously defined as a title or is it a book? This compared to issue #135 confused us since we first were dealt both.
