### ISSUE TITLE
Assign specific role to user

### ISSUE THREAD

**Issue by itggot-linus-styren** [itggot-TE4/Yabs#142]
## Description
Instead of there being named roles such as "Elev" and "Lärare", there should be a role number with mapping.

## DoD:
- The different roles available are saved using bitwise
- Helper methods are implemented to check role authorization

## Context
Relates to #51
Might be another solution using pundit built in role system
Discuss with @itggot-TE4/green-team for rails migration issue #139

**Comment by TE4-jacob-lundberg** [comment]
The google api does not provide us with a role, the only difference we can see is if the user is a member of staff or a student. Unless something changes we currently see no way to implement a more complex role system. Closing until further notice.

**Comment by itggot-linus-styren** [comment]
Why is this closed? According to the specs there should be a administrator role that can assign multiple roles. There should be a possibility for a `staff` to be assigned specific roles manually.
