### ISSUE TITLE
Search for users and see their info and card

### ISSUE THREAD

**Issue by itggot-linus-styren** [itggot-TE4/Yabs#143]
## Description:
The principal should be able to search for specific users and loans.

## DoD:
- [x] You can search for users
- [x] You can only search for users as a teacher or further up the foodchain, for example the principle or attendant (vaktmästare).
- [x] You can press on the user and get redirected to the user's route. (#300) 

## Context:
Talk to @itggot-TE4/green-team about authorisation with pundit.
Relates to #113
Relates to #185
Relates to #300

**Comment by TE4-Daniel-Kull** [comment]
We can cooperate on this issue. I changed LoanSearch into SearchList (a generic component) we could use this to find users too. See #184.

**Comment by itggot-linus-styren** [comment]
@TE4-Daniel-Kull can this be closed and split into a new issue for remaining tasks?
