### ISSUE TITLE
Users can post content without being authenticated

### ISSUE THREAD

**Issue by TE4-Mattis-Abrahamsson** [itggot-TE4/Yabs#150]
**Describe the bug**
I was able to create titles, books & generate ID cards without being logged in

**To Reproduce**
1. Create a resource without being authenticated by google

**Expected behavior**
- Not being able to see the routes
- Not being able to post e.g. auth is needed on both the front- and backend

## Context
Duplicate of #160

**Comment by TE4-jacob-lundberg** [comment]
The opportunity to fix this should be implemented in #142, at least on the backend side.

**Comment by itggot-linus-styren** [comment]
@TE4-Mattis-Abrahamsson is this fixed?

**Comment by TE4-Mattis-Abrahamsson** [comment]
@itggot-linus-styren I think it's implemented on the backend but the view needs to be protected as well
