### ISSUE TITLE
Add tests for search titles, assign status, and register book

### ISSUE THREAD

**Issue by TE4-william-bruun** [itggot-TE4/Yabs#151]
**Is your feature request related to a problem? Please describe.**
Tests need to be created in order for the "fake it till you make it" motto to be followed

**DoD**
- Unit tests for each component

**Additional context**
If help is needed ask the QA or try to find the answer on the net.
Coordinate with Team Green.

**Comment by itggot-linus-styren** [comment]
Talk to @TE4-jacob-lundberg regarding this issue.
