### ISSUE TITLE
Skapa en pre commit hook som förhindrar att vår secret läggs upp på github.

### ISSUE THREAD

**Issue by TE4-william-bruun** [itggot-TE4/Yabs#154]
## Reason
Det finns en fil som kommer att förstöra våra chanser att arbeta med detta om någon råkar att pusha up den. Därför kommer vi skapa en hook som kollar ifall den filen är i commiten och stoppar den ifall den är det.

## DoD
- Stoppar secrets.yml från att läggas till I en commit

## Context
Om någon råkar göra detta kommer vi behöva vänta i ett par månader med att börja arbeta igen.

**Comment by TE4-william-bruun** [comment]
Jag har två ideer som gäller när det kommer till att lösa detta, den ena är mer relaterad en den andra. 

Den första är att göra en pre-push hook som kan hindra folk från att pusha up direkt till master, och därmed develop, så att vi tvingas följa den standarden. 

Den andra ideen är istället för att ha backend/config/secrets.yml i gitignore så kan man stoppa den i exclude filen som finns i .git/info, på detta vis kan man minska kluttret som finns i gitignore.

**Comment by TE4-arvid-nilber** [comment]
Denna fil ligger redan i gitignoren så om ingen tar bort gitignoren medvetet och pushar upp filen så kommer ingen skada att ske.
