### ISSUE TITLE
Organize TS types

### ISSUE THREAD

**Issue by TE4-Mattis-Abrahamsson** [itggot-TE4/Yabs#177]
**Is your feature request related to a problem? Please describe.**
Types are currently scattered across multiple modules and what not

**DoD**
All types will be moved to a types.ts file (see: https://stackoverflow.com/questions/36633033/how-to-organize-typescript-interfaces)

## Context
~~Blocked by #168~~
Could be worked on parallel with the documentation issue #203

**Comment by itggot-linus-styren** [comment]
Status update?
