### ISSUE TITLE
pug to normal

### ISSUE THREAD

**Issue by te4-gabriel-stark** [itggot-TE4/Yabs#181]
**Is your feature request related to a problem? Please describe.**
Pug sucks, remove it.

**DoD**
- Pug is no more.

**Comment by itggot-linus-styren** [comment]
![](https://previews.123rf.com/images/fongleon356/fongleon3561701/fongleon356170100076/69355533-sad-pug-dog-sitting-on-floor-indoor-with-tongue-sticking-out-the-pug-is-a-small-breed-of-domestic-do.jpg)
