### ISSUE TITLE
Backend for loans returns error code 500

### ISSUE THREAD

**Issue by TE4-oskar-pilborg** [itggot-TE4/Yabs#192]
**Description** 
I can't work on profile page due to problems with loans in backend. 

**DoD**
- route: api/v1/loans doesn't return error 500 internal server error

**Additional context**
Talk to me plz

**Comment by te4-gabriel-stark** [comment]
When i use @Te4-Alexander-Nilsson-Melbostads branch i don't seem to get this issue, it still doesn't work but not due to the backend.
Relates to #190 
Possibly fixed by #190

**Comment by te4-gabriel-stark** [comment]
Can't seem to reproduce this bug, maybe it's local and if that's the case, can i close it?

**Comment by te4-gabriel-stark** [comment]
<img width="673" alt="Screenshot 2019-12-12 at 13 46 23" src="https://user-images.githubusercontent.com/47849500/70713252-e0090f00-1ce5-11ea-92be-f87c7c1e5002.png">
<img width="1436" alt="Screenshot 2019-12-12 at 13 45 54" src="https://user-images.githubusercontent.com/47849500/70713258-e39c9600-1ce5-11ea-9648-1694e7ca9f93.png">
This is what i get.
I used the following commands in the backend folder:
rails db:schema:load
rails db:reset
rails s

Maybe try these and it will work?

**Comment by itggot-linus-styren** [comment]
@TE4-oskar-pilborg can this be closed?

**Comment by TE4-oskar-pilborg** [comment]
Yes i don't have it
