### ISSUE TITLE
Update db to accommodate 'ämnesansvariga'

### ISSUE THREAD

**Issue by TE4-jacob-lundberg** [itggot-TE4/Yabs#217]
**Is your feature request related to a problem? Please describe.**
We need to update our db to work with new relations in order to implement this.

**DoD**
- A table with user/subject relation exists
- Update title table to record subject of the title

**Additional context**
Might be more tables that need change. Unsure at the time of creating this.

**Comment by itggot-linus-styren** [comment]
Talk to @TE4-arvid-nilber
