### ISSUE TITLE
Backend tests throws unexpected errors

### ISSUE THREAD

**Issue by TE4-emanuel-strom** [itggot-TE4/Yabs#222]
## Description
Error: 'NoMethodError: undefined method `>' for nil:NilClass'
is thrown in tests for LoansController and UserController.

Error: Expected response to be a <2XX: success>, but was a <422: Unprocessable Entity>
## DoD
- Tests that should pass no longer throws errors.

**Comment by itggot-linus-styren** [comment]
Looking at the output of backend-unit-tests job I only see a error related to status code 422:
```
# Running:

.....F

Failure:

LoansControllerTest#test_should_show_loan [/Users/runner/runners/2.162.0/work/Yabs/Yabs/backend/test/controllers/loans_controller_test.rb:23]:

Expected response to be a <2XX: success>, but was a <422: Unprocessable Entity>

Response body: {}

rails test test/controllers/loans_controller_test.rb:21
```
