### ISSUE TITLE
Add cypress videos and screenshots to gitignore

### ISSUE THREAD

**Issue by te4-david-petersson** [itggot-TE4/Yabs#262]
**Is your feature request related to a problem? Please describe.**
Cypress videos and screenshots of running tests are not exactly something we want to push to github. Everyone should have their own, local videos and/or screenshots of tests.

**DoD**
- Added cypress videos to gitignore.
- Added cypress screenshots to gitignore
- They aren't pushed to github.

**Additional context**

**Comment by itggot-linus-styren** [comment]
@te4-david-petersson is this done?
