### ISSUE TITLE
Fixtures should work like snapshots

### ISSUE THREAD

**Issue by TE4-emanuel-strom** [itggot-TE4/Yabs#267]
**Is your feature request related to a problem? Please describe.**
Whenever people run the tests locally, the fixtures are updated unnecessarily.

**DoD**
- Set flag when to update fixtures
- Flag should be false by default

**Additional context**
test/fixtures/* is causing a lot of merge conflicts.

**Comment by itggot-linus-styren** [comment]
See https://stackoverflow.com/a/14450473

**Comment by itggot-linus-styren** [comment]
The environment argument could be `fixtures` with a possible set of values (all, books, loans, titles etc.)
