### ISSUE TITLE
Refactor API helpers

### ISSUE THREAD

**Issue by itggot-linus-styren** [itggot-TE4/Yabs#271]
## Description
Convert API helpers to singleton class instead of exporting to object.

~~Use DI for all helpers (e.g API services): https://github.com/inversify/InversifyJS~~

Move api folder to helpers/services

## DoD:
- All API:s are class based
- All API files are moved to either helpers/services
- No functionality is changed

**Comment by TE4-Mattis-Abrahamsson** [comment]
Maybe move them to "services" instead?
