### ISSUE TITLE
Problem with cigcanvas.vue file

### ISSUE THREAD

**Issue by TE4-oskar-pilborg** [itggot-TE4/Yabs#280]
I can't write my tests because savePicture method can't send data to usermodule.update method.
The error comes from update method takes in argument which is interface: userform but the data sent from savePicture is only uid/ this.barcode and the image which is not declared apparently. 
So I would like to discuss this with someone who have worked in this file earlier during the project. plz help 🙏

**Comment by itggot-linus-styren** [comment]
According to GitHub, @TE4-Mattis-Abrahamsson has edited CigCanvas.vue most recently.

**Comment by itggot-linus-styren** [comment]
Also more information in https://github.com/itggot-TE4/Yabs/commit/b345203496c5669c67c3cfb6fa0cc668c831dbc0

Also the interface UserForm doesn't seem to be used, I can only see that FormData is used which is a builtin type.

**Comment by TE4-Mattis-Abrahamsson** [comment]
oops, did I break something?

**Comment by TE4-Mattis-Abrahamsson** [comment]
Should be fixed by #290
