### ISSUE TITLE
Fix yarn build not working

### ISSUE THREAD

**Issue by TE4-jacob-lundberg** [itggot-TE4/Yabs#281]
**Describe the bug**
When trying to build the application the following errors appear 

> /modules/UsersModule"' has no exported member 'User'.

This is also visible during yarn serves.
This prevents our integration tests from running.

**To Reproduce**
1. $ yarn serve
2. Watch errors in terminal

**Expected behavior**
Terminal is empty of errors and build is completed.

**Comment by TE4-jacob-lundberg** [comment]
After investigation this seems to be due to the interfaces being moved into another file

**Comment by itggot-linus-styren** [comment]
This was introduced by #278
