### ISSUE TITLE
CigCanvas renders role number before choosing user

### ISSUE THREAD

**Issue by TE4-Mattis-Abrahamsson** [itggot-TE4/Yabs#293]
**Describe the bug**
When choosing an image, the image along with the role number will render

**To Reproduce**
1. Go to /admin/cards
2. Upload an image
3. Notice that the image along with the role number has rendered

**Expected behavior**
No role number until you choose a user.
Role as text instead of number.

**Comment by TE4-jacob-lundberg** [comment]
On my screen, the role number isn't being translated to text, it stays in its number form.
