### ISSUE TITLE
Add routing when pressing on an user in a list.

### ISSUE THREAD

**Issue by TE4-Daniel-Kull** [itggot-TE4/Yabs#300]
**Is your feature request related to a problem? Please describe.**
We need a visual way to route to a user's profile.

**DoD**
- [ ] The admin can click on a user in the list and be routed to the user's route.

**Additional context**
Working in UserListComponent.vue

**Comment by itggot-linus-styren** [comment]
![](https://1.bp.blogspot.com/-BvINf3EALEk/Vd1Zj32DQnI/AAAAAAAACT8/2Ia9vVfhgH4/s1600/6b209a06b4f48e353a3afdcc04a4b51c.jpg)
sorry....
