### ISSUE TITLE
Register Books

### ISSUE THREAD

**Issue by te4-alexander-kjellberg1** [itggot-TE4/Yabs#356]
## ✨ Feature request
Admins can register new books

### 📇 User story
As an admin I want to be able to register new books with a unique barcode  

### 📜 Acceptance Criteria
- [ ] An admin can register new books
- [ ] An admin receives feedback if book was/wasn't registered properly
- [ ] Newly registered titles are added to corresponding data-table

### 💡 Additional context
These books gets a unique barcode.

**Comment by te4-adrian-almetun-smeds** [comment]
Complete
