### ISSUE TITLE
Search among titles and books

### ISSUE THREAD

**Issue by Te4-Mahdi-Alizadah** [itggot-TE4/Yabs#359]
## ✨ Feature request
Make user possible to search titles and books

### 📇 User story
As a user I want to find the book/title i want to borrow.

### 📜 Acceptance Criteria
- [ ] Investigate existing search functionality
- [ ] Search function and showing result to searcher.

**Comment by te4-alexander-kjellberg1** [comment]
I belive that this is solved by the component already.
