### ISSUE TITLE
Able to view ongoing book loans

### ISSUE THREAD

**Issue by TE4-Filip-Liljenberg** [itggot-TE4/Yabs#361]
## ✨ Feature request
When the user is logged in, the user can see the books which he has borrowed.

### 📇 User story
As a user I want to be able to see the books that I have borrowed.

### 📜 Acceptance Criteria
- [x] Investigate existing functionality to see if loans can be viewed.
- [x] The user can se the books that he borrowed.

**Comment by te4-david-jensen** [comment]
Please remove the swenglish from this issue.

**Comment by te4-andre-skvarc** [comment]
This issue was the most wasted time of my life. Because I started building a new axios call that I got to work and everything. When the app already had a functioning axios caller... Hmmmm
