### ISSUE TITLE
Add subject_id in post when creating new title

### ISSUE THREAD

**Issue by te4-jonathan-ronsten** [itggot-TE4/Yabs#371]
## ✨ Feature request
Not passing along a subject_id causes the application to do nothing, 

### 📇 User story
As a user I want to be able to create a new title

### 📜 Acceptance Criteria
A list of changes that need to be implemented to consider this feature done.
- [ ] Adds subject_id in post when creating new title.
- [ ] Adding new title updates DB and shows the newly created title

**Comment by itggot-linus-styren** [comment]
After this fix the cypress test might need to be updated to verify that a title has been created successfully. Related to #39
