### ISSUE TITLE
Setup tests for creating titles and books.

### ISSUE THREAD

**Issue by itggot-linus-styren** [itggot-TE4/Yabs#39]
## Description
Use E2E with Cypress testing

## DoD:
- Test which creates title and books with cypress.
- Add test routes on backend for login.

## Context:
Talk to @itggot-TE4/red-team

**Comment by te4-Leo-Wahlandt** [comment]
This issue is closed, #171 is the solution

**Comment by itggot-linus-styren** [comment]
Talk to @itggot-TE4/red-team about adding test routes encapsulated by Rails.env.test?
