### ISSUE TITLE
Investigation: Are we affected by the deprecation of set-env and add-path in our actions

### ISSUE THREAD

**Issue by te4-adrian-almetun-smeds** [itggot-TE4/Yabs#397]
# GitHub Actions: Deprecating set-env and add-path commands
See: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

How are we affected by this and if so what actions do we have to take?

**Comment by itggot-linus-styren** [comment]
This line had to be added to make the integration test pass:

https://github.com/itggot-TE4/Yabs/blob/54af93bd4a7a7afe06fde1bcb17f12787948ac4e/.github/workflows/integration.yml#L46

Failed integration test log might give a clue: https://github.com/itggot-TE4/Yabs/actions/runs/405972355

**Comment by te4-adrian-almetun-smeds** [comment]
The errors referenced in https://github.com/itggot-TE4/Yabs/actions/runs/405972355 are likely coming from the current action used for getting our ruby env setup. It uses the add-path command witch is being deprecated soon. And the action we are currently running have been depreciated for a while now.

I'd suggest we make the move over to [setup-ruby](https://github.com/ruby/setup-ruby).

**Comment by te4-adrian-almetun-smeds** [comment]
Closing in favour of #428
