### ISSUE TITLE
Running Integration tests before merging to develop instead of on push

### ISSUE THREAD

**Issue by te4-adrian-almetun-smeds** [itggot-TE4/Yabs#398]
Currently our E2E test are run at midnight and on push to develop. What would be more reasonable would be to run them prior to merging it into master to not fail first when the branch has already been merged. Thus not ensuring increased stability on the develop branch.

Currently we can merge to develop and it's first after the merge that the tests run and potentially fail. But by then it's already to late :/ 

## Proposal
* Switch to run our E2E and API tests on `pull_request` in addition or in place of the current on `push`

## Potentially negative aspects
* These tests are going to run allot more frequently meaning it's going to use more of the GH Action resources. The question here is if this is a limitation for the organization or if we are able to do this.

## Positive aspects
* The tests runs before we merge the branch, thus preventing failure when on `develop`.

**Comment by itggot-linus-styren** [comment]
Good point, perhaps running integration tests locally should be part of the definition of done for all tickets. I think there is no limit of max minutes of GA workflows for public repos: https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-billing-and-payments-on-github/managing-your-spending-limit-for-github-actions#about-spending-limits-for-github-actions

Only storage is limited to 2GB, Doesn't look like we are using any atm:
![image](https://user-images.githubusercontent.com/23553553/101740658-6c9d0780-3ac9-11eb-86a4-06726e4626d9.png)


Perhaps artifacts could be uploaded only on the schedule and push triggers? This could save some storage.
