### ISSUE TITLE
Postman test body is not valid

### ISSUE THREAD

**Issue by te4-david-jensen** [itggot-TE4/Yabs#404]
### Description
The bodies of several postman tests are invalid, as they no longer go to a valid database entry. There is also a discrepancy in the time formats between what is found in request bodies and the database.

### Expected behavior
The requests should give a status code of 200, but instead give a code of 422 or 404.

## 🔬 To Reproduce
1. Run 'Yabs' collection in postman
2. See errors
Alt:
1. Open 'Yabs' collection in postman
2. Look in request body for 'Single user' (example)
3. Open database
4. Inspect table: 'users'
5. Compare timestamp-formatting
6. Look for user in request body

**Comment by itggot-linus-styren** [comment]
Before running postman tests, try using rails db:setup and then rails db:fixtures:load instead of running directly from seeder.

**Comment by te4-david-jensen** [comment]
> Before running postman tests, try using rails db:setup and then rails db:fixtures:load instead of running directly from seeder.

Unfortunately, `$ rails db:setup` crashes because the database is locked.

**Comment by te4-david-jensen** [comment]
The postman issues were due to an inherent inability to authenticate yourself to google's API through postman. This can be resolved by adding `- RAILS_ENV=test` below `- BUNDLE_PATH=/bundle/vendor` in 'docker-compose.yml'
