### ISSUE TITLE
Rework card and user ID

### ISSUE THREAD

**Issue by te4-alexander-nylundgomes** [itggot-TE4/Yabs#417]
## Description
Rework card so that it is not reliant to Google token. It should instead have its own ID connected to the user ID.

## Acceptance criteria
- [x] The card is disconnected from Google and connected to its user via user ID instead.
- [x] Availability to change card for user.

## solution proposal
Create a separate table in the db for connecting card_id to user_id this can also contain metadata for the card.

**Comment by itggot-linus-styren** [comment]
Relates to #399
