### ISSUE TITLE
Add save all button in card generation (CanvasContainer.vue)

### ISSUE THREAD

**Issue by te4-alexander-nylundgomes** [itggot-TE4/Yabs#420]
## Description
Currently, there is only the ability to save on image from the card generation. It should also be possible to save all at once in corresponding image folders. 

## Acceptance criteria
- [ ] Functionality to save all images at once from card generation.

**Comment by itggot-linus-styren** [comment]
Main card save functionality broken, needs investigation. To be created by @te4-dennis-christensen
