### ISSUE TITLE
Create title test fails in CI

### ISSUE THREAD

**Issue by itggot-linus-styren** [itggot-TE4/Yabs#448]
### Description
After create title test was changed in #405, integration job running in CI pipeline shows a failure.

## 🔬 To Reproduce
1. Create a PR on this project
2. Wait for GA to run integration job.
3. Check error log and artifacts to see the problem.

### 🔥 Exception or error
Backend returns 500 error. Artifact for rails log is not available (in backend/log), should be added to e2e job in GA. Also see https://github.com/itggot-TE4/Yabs/runs/1537679824
### 📷 Screenshots
![This test will create a title and a book -- Creates a title and reset the fields when added (failed)](https://user-images.githubusercontent.com/23553553/101925177-e02a3c00-3bd1-11eb-881a-10226ede9e2f.png)

**Comment by te4-adrian-almetun-smeds** [comment]
Will be solved alongside #371
