### ISSUE TITLE
Refactor all Book components

### ISSUE THREAD

**Issue by te4-henrik-stahl** [itggot-TE4/Yabs#461]
## ✨ Feature request
Use composition api instead

### 📜 Acceptance Criteria
- [x] BookCondition refactored
- [x] BookForm refactored
- [x] BookList refactored

**Comment by te4-adrian-almetun-smeds** [comment]
@te4-henrik-stahl Can you confirm if this was resolved in #566 ?

**Comment by te4-henrik-stahl** [comment]
Yes all the book components are refactored
