### ISSUE TITLE
Write unit test for LoanFormComponent

### ISSUE THREAD

**Issue by Jacob-sandstrom** [itggot-TE4/Yabs#475]
## ✨ Feature request
This is an existing test that requires updating.
The bookConditionComponent requires working tests.

### 📇 User story
As a user I want to know that everything will work, because it has been tested properly. 

### 📜 Acceptance Criteria
- [ ]  There should be 50% code coverage on this component
- [ ] - [ ] (Here there should be more precise part goals for the test, what smaller things the test needs to test)

### 💡 Additional context
Handbook: 
https://lmiller1990.github.io/vue-testing-handbook/
See current test coverage:
https://codeclimate.com/github/itggot-TE4/Yabs

**Comment by ntijoh-Erik-Albinsson** [comment]
LoanFormComponent has 54% coverage.
