### ISSUE TITLE
LoanListComponent

### ISSUE THREAD

**Issue by Te4-Jacob-sandstrom** [itggot-TE4/Yabs#476]
## ✨ Feature request
Update an existing test.
I want to know ~~if~~ when I break stuff.

### 📜 Acceptance Criteria
- [ ]  There should be 50% code coverage on this component

### 💡 Additional context
https://lmiller1990.github.io/vue-testing-handbook/

**Comment by te4-andre-skvarc** [comment]
This component is already covered in https://github.com/itggot-TE4/Yabs/issues/425
