### ISSUE TITLE
Add unit tests for libraryLoanCompoent

### ISSUE THREAD

**Issue by te4-adrian-almetun-smeds** [itggot-TE4/Yabs#482]
## ✨ Feature request
I want to know ~~if~~ when I break stuff.

### 📜 Acceptance Criteria
- [ ]  There should be 50% code coverage on this component

### 💡 Additional context
https://lmiller1990.github.io/vue-testing-handbook/

**Comment by te4-andre-skvarc** [comment]
Started on this issue, see the error message it throws. This code is pushed to this branch.
<img width="929" alt="Screenshot 2021-01-15 at 14 36 01" src="https://user-images.githubusercontent.com/43438011/104734034-e915ac80-573f-11eb-97eb-0e2ef10534a3.png">
