### ISSUE TITLE
It's possible to create multiple titles containing the same ISBN

### ISSUE THREAD

**Issue by te4-adrian-almetun-smeds** [itggot-TE4/Yabs#492]
### Description
There seems like there is a possibility to create multiple titles with the same ISBN identifier.

### Expected behavior
There should only be one title for a specific ISBN

## 🔬 To Reproduce
1. Create a title in the admin titles view
2. Create another one with the same ISBN number
3. Check the title list. There are now two.

### 💡 Additional context
The ISBN column in the db should probably be set to UNIQUE

**Comment by itggot-linus-styren** [comment]
Should probably be done along with https://github.com/itggot-TE4/Yabs/projects/4#card-50900303
