### ISSUE TITLE
Switch to use a postgres database

### ISSUE THREAD

**Issue by te4-adrian-almetun-smeds** [itggot-TE4/Yabs#548]
## ✨ Feature request
We need to improve our concurrency.
We need to move to a "proper" database for production.

### 📇 User story
As a user I don't like being waiting for others while  they make database queries.

### 📜 Acceptance Criteria
- [ ]  Switch out sqlite for postgres
- [ ] Include postgres in the docker compose setup for easy deployment

### 💡 Additional context
Allows #547 and #594 to be merged

**Comment by itggot-linus-styren** [comment]
Useful resources:
https://dev.to/forksofpower/make-the-move-from-sqlite3-to-postgres-in-rails-6-34m2
https://docs.docker.com/compose/rails/
