### ISSUE TITLE
Add respective books to respective teacher in their Profile

### ISSUE THREAD

**Issue by TE4-Rasmus-Brednert** [itggot-TE4/Yabs#573]
As a teacher, you want to access all your coursebooks in your profile

- [ ] Overview of books

- [ ] Which books are borrowed/not borrowed?

- [ ] Which student borrowed it?

**Comment by te4-adrian-almetun-smeds** [comment]
Can you add a description to this issue so we can get a little more details on how this is supposed to be implemented?

**Comment by te4-adrian-almetun-smeds** [comment]
ping @itggot-TE4/red-team
