### ISSUE TITLE
Refactor LoansModule

### ISSUE THREAD

**Issue by te4-alexander-kjellberg** [itggot-TE4/Yabs#622]
### Description
Future-proof the code by refactoring store modules from Vuex[?] to Vue3[?]. 

### Acceptance Criteria
- [ ] LoansModule is future-proofed and no longer uses vuex. 
- [ ] Nothing is broken and all functionality is the same.

**Comment by te4-adrian-almetun-smeds** [comment]
Duplicate of #392
