### ISSUE TITLE
Almost identical methods in Loans Api Service 

### ISSUE THREAD

**Issue by te4-adrian-almetun-smeds** [itggot-TE4/Yabs#640]
## Background
Why are there two almost identical methods with different types:
https://github.com/itggot-TE4/Yabs/blob/51765cf64d7dc17a2e726d6cc67a76b0d3936f65/frontend/src/services/api/loans.ts#L14-L28

The first one is using LoanForm and the other one is using AddLoanForm?

_Originally posted by @itggot-linus-styren in https://github.com/itggot-TE4/Yabs/issues/602#issuecomment-760072010_

## Acceptance criteria
- Investigate weather or not these can be merged into a single function.
- If above was possible, they should be merged and any references should be updated

**Comment by itggot-linus-styren** [comment]
Looks like it was added in #579 but never used
