### ISSUE TITLE
Cards should be generated with a unique id instead of  the users id

### ISSUE THREAD

**Issue by Jacob-sandstrom** [itggot-TE4/Yabs#646]
### Acceptance criteria
- [ ] Cards are generated with a barcode containing a unique card id instead of a user id

### Additional context 
- requires change to the documentation

**Comment by ntijoh-daniel-berg** [comment]
What improvements would having a unique id per _card_ (as opposed a user´s cards all having the same id) would bring?
I with separating the card id from the user´s id though.

**Comment by ntijoh-Erik-Albinsson** [comment]
If you would for some reason need multiple cards per user, and accidentally lose one of them, a unique id could be beneficial when deactivating a card. However it is not immediately clear if this change would be necessary in a practical use. Unless this change is necessary to solve a different issue it should perhaps be left be.
