### ISSUE TITLE
Sort by nearest date, LoanListComponent

### ISSUE THREAD

**Issue by ntijoh-Erik-Albinsson** [itggot-TE4/Yabs#716]
## ✨ Feature request
When viewing loaned books, the books should be sorted by the date in which they need to be returned. 

### 📇 User story
This will make it easier for the user to have control and an overview of which book is most urgent to be returned.

### 📜 Acceptance Criteria
The change should probably be made to LoanListComponent, and the issue is considered resolved once the loaned books are sorted from shortest time left by default.

**Comment by ntijoh-daniel-berg** [comment]
Can also be implemented in backend, but maybe you want to be able to sort the list in the frontend anyways
