### ISSUE TITLE
Change English on website to Swedish

### ISSUE THREAD

**Issue by ntijoh-Erik-Albinsson** [itggot-TE4/Yabs#718]
## ✨ Feature request
Currently different titles and descriptions are mixed with the both languages. Since the website is developed for use by Swedes the website should be in Swedish. 

### 📜 Acceptance Criteria
Everything readable by the user should be in Swedish, except routes.

**Comment by ntijoh-daniel-berg** [comment]
This should be done through an internationalization library. Maybe https://kazupon.github.io/vue-i18n/?
