### ISSUE TITLE
Remake css for start page.

### ISSUE THREAD

**Issue by ntijoh-linus-bjorken** [itggot-TE4/Yabs#723]
:shipit:
The css on the start page is not to be tolerated. It's difficult to understand which text is connected to which button.

Idea to how it should be changed. Move the title and text to tile up a bit and place button text over button. Also make the buttons smaller in width and center the text.

**Comment by ntijoh-daniel-berg** [comment]
Is this a css problem or is it just the Vuetify components being used in the wrong way?

**Comment by ntijoh-nikki-andersson** [comment]
Perhaps? We will investigate

**Comment by ntijoh-nikki-andersson** [comment]
Seems like someone set width: inherit on the .row-btn class, which made the buttons look hideous.
