### ISSUE TITLE
AddLoanComponent feature bug

### ISSUE THREAD

**Issue by ntijoh-evelina-karlsson** [itggot-TE4/Yabs#725]
### Description
The v-model connected to the input of AddLoanComponent is bugged and returns [object Object] as default. This further results in articles not being able to be scanned. The OK button seems to not be linked to any type of action.

## 🔬 To Reproduce
Steps to reproduce the behaviour:
-The input field should be empty
-The book should be scanned
-The barcode numbers of the book should appear in the input field
-Clicking OK should result in some type of visual action

**Comment by ntijoh-daniel-berg** [comment]
> The OK button seems to 

Seems to what?
