### ISSUE TITLE
Create UX flow for adding multiple loans at a time.

### ISSUE THREAD

**Issue by itggot-linus-styren** [itggot-TE4/Yabs#74]
## Description
There should be a way to assign multiple loans at the same time (e.g a whole class).

## Acceptance criteria:
- [ ] assign title
- [ ] scan barcode for book
- [ ] scan barcode for user
- [ ] Update wiki when feature is complete

## Context
See branch 74-multiple-loans for status update.

**Comment by itggot-linus-styren** [comment]
https://github.com/itggot-TE4/Yabs/commit/098136c49bb71a8023d9655cc88fb2335b0f4a11

**Comment by itggot-linus-styren** [comment]
Talk to @itggot-TE4/blue-team or @itggot-TE4/red-team for support

**Comment by te4-adrian-almetun-smeds** [comment]
Could possibly make use of #615

**Comment by te4-adrian-almetun-smeds** [comment]
See `feature/74-multi-loan` for implementation. Awaiting merge of #602
