### ISSUE TITLE
Remove BarcodeReaderComponent and button toggling the component

### ISSUE THREAD

**Issue by ntijoh-nikki-andersson** [itggot-TE4/Yabs#750]
:shipit:
The supposed purpose of this component is to open the camera and scan barcodes with some kind of extension or plugin. 
This currently doesn't work, and I'm not sure if it's necessary.

**Comment by ntijoh-nikki-andersson** [comment]
Personally it feels unnecessary, since the library will have a computer with a barcode scanner. And since all the books the students can loan is in the library, there isn't really a need for an app or website for the students to scan and loan books. There might be a need for it for the teachers when lending out academic books since they probably won't be in the library, but it shouldn't be an issue either if the teacher room has a personal physical barcode scanner, which can easily be plugged in.

**Comment by ntijoh-Erik-Albinsson** [comment]
The issue has been resolved, the component is now working, so it isn't a problem anymore
