### ISSUE TITLE
Routes should be inaccessible when not logged in

### ISSUE THREAD

**Issue by ntijoh-nikki-andersson** [itggot-TE4/Yabs#758]
### Description
All routes except the landing page (/) should have v-if that checks if the user is logged in, just like what is being used in ProfileView.

### Expected behaviour
If the user is not logged in it shows an error message instead of the page.
## 🔬 To Reproduce
Steps to reproduce the behaviour:
1. Go to '/admin' (for example) without logging in
2. The default view shows, instead of a error message

### 📷 Screenshots
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/56922646/145996679-1b85f184-073e-446e-b759-d6ebcb42db1d.png">

**Comment by Linkaan** [comment]
Also see #246
