### ISSUE TITLE
All E2E tests failing after change #763

### ISSUE THREAD

**Issue by olantig** [itggot-TE4/Yabs#771]
### Description
Since change #763 all e2e tests are failing. The UI isn't visible until user (test runner) are logged in.

**Comment by olantig** [comment]
See https://github.com/itggot-TE4/Yabs/pull/768#issuecomment-994574769

**Comment by Linkaan** [comment]
Some suggestions on how to run cypress within docker
- Setup X11 forwarding: https://github.com/bahmutov/cypress-open-from-docker-compose
- Setup VNC and connect to docker container: https://qxf2.com/blog/view-docker-container-display-using-vnc-viewer/

Why can't you run cypress on your host machine? Installing cypress and running it within the frontend folder should work.

**Comment by Linkaan** [comment]
Another issue in #779 is the cypress tests not being updated with new route. The following change needs to be done in addLoan.js, LibraryTest.js and ReturnBook.spec.js
```diff
- baseVisit('/library/Interface');
+ baseVisit('/library-interface');
```

**Comment by ntijoh-nikki-andersson** [comment]
Made a pull-request about that now, thank you
