### ISSUE TITLE
Bookformcomponent breaking when scanning barcode

### ISSUE THREAD

**Issue by ntijoh-Erik-Albinsson** [itggot-TE4/Yabs#805]
### Description
When creating a book, scanning the barcode automatically tries to submit the form, which results in a rollback in the database. This breaks the form so that you need to reload that route in order to submit the form, otherwise it results in an error 422.

### 💡 Additional context
BookFormComponent
https://www.keycdn.com/support/422-unprocessable-entity

**Comment by ntijoh-nikki-andersson** [comment]
Solved in #806
