### ISSUE TITLE
Create single reference between new books and titles.

### ISSUE THREAD

**Issue by itggot-linus-styren** [itggot-TE4/Yabs#96]
## Description
There should be a way to select a title for the new book created.

## DoD:
- When a new book is created a title can be assigned to it.

## Context
Resolves #170

**Comment by TE4-Mattis-Abrahamsson** [comment]
@itggot-linus-styren When posting a new book, a title_id is already being assigned to the resource, so what exactly does this issue refer to?

**Comment by itggot-linus-styren** [comment]
What is the response from the post request to the server? Does it include the title as a nested resource?

**Comment by TE4-Mattis-Abrahamsson** [comment]
@itggot-linus-styren I checked and the title resource is returned as well, closing the issue

**Comment by TE4-Mattis-Abrahamsson** [comment]
@itggot-linus-styren I checked and the title resource is returned as well, closing the issue
