### ISSUE TITLE
add types for Vuex modules

### ISSUE THREAD

**Issue by simon-ulrik** [itggot-TE4/Yabs#99]
## Description
Use typescript interfaces for frontend vuex modules

## DoD:
- TS interfaces have been added for as many resources as possible
- Remove the use of :any as much as possible

## Context:
Relates to #80
Relates to #177 
Blocked by #138

**Comment by te4-Leo-Wahlandt** [comment]
Isn't this a duplicate issue, the #177 looks quiet similar

**Comment by itggot-linus-styren** [comment]
Fixed by #268
